http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  farms:
    paths:
      - /farms
      - /farms/*
serviceEndpoints:
  farms-service:
    url: https://my-json-server.typicode.com/marmicode/farmicode-api/farms
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - '@marmicode/eg-openapi-request-validator'
pipelines:
  farms:
    apiEndpoints:
      - farms
    policies:
      - '@marmicode/eg-openapi-request-validator':
          action:
            openapiSpecPath: config/farmicode.yaml
      - proxy:
          action:
            serviceEndpoint: farms-service
            stripPath: true # Hit `/farms` instead of `/farms/farms`

