http:
  port: 8080
  host: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  farmicode:
    host: localhost
    paths: '/farmicode/*'
serviceEndpoints:
  farmicode:
    url: https://my-json-server.typicode.com/marmicode/farmicode-api
policies:
  - openapi-request-validator
  - openapi-openid-connect
  - proxy
pipelines:
  - name: farmicode
    apiEndpoints:
      - farmicode
    policies:
      - openapi-openid-connect:
          - action:
              audience: 'https://sheep.marmicode.io'
              openapiSpecPath: ./config/farmicode.yaml
      - openapi-request-validator:
          - action:
              openapiSpecPath: ./config/farmicode.yaml
      - proxy:
          - action:
              serviceEndpoint: farmicode
              changeOrigin: true
              stripPath: true
