http:
  port: 8080
  host: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  farmicode:
    host: localhost
    paths: '/farmicode/*'
serviceEndpoints:
  farmicode:
    url: https://my-json-server.typicode.com/marmicode/farmicode-api
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: farmicode
    apiEndpoints:
      - farmicode
    policies:
      - proxy:
          - action:
              serviceEndpoint: farmicode
              changeOrigin: true
              stripPath: true
