http:
  port: 8080
  host: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  farmicode:
    host: localhost
    paths: '/farmicode/*'
serviceEndpoints:
  farmicode:
    url: https://my-json-server.typicode.com/marmicode/farmicode-api
policies:
  - logger
  - openapi-request-validator
  - openapi-openid-connect
  - proxy
  - rate-limit
pipelines:
  - name: farmicode
    apiEndpoints:
      - farmicode
    policies:
      - logger: []
      - openapi-openid-connect:
          - action:
              audience: 'https://farmicode.io'
              openapiSpecPath: ./config/farmicode.yaml
      - rate-limit:
          - action:
              max: 10
              windowMs: 30000
              rateLimitBy: '${req.user?.id}'
      - openapi-request-validator:
          - action:
              openapiSpecPath: ./config/farmicode.yaml
      - proxy:
          - action:
              serviceEndpoint: farmicode
              changeOrigin: true
              stripPath: true
