# Core
db:
  redis:
    emulate: true
    namespace: EG

#plugins:
# express-gateway-plugin-example:
#   param1: 'param from system.config'

plugins:
  '@marmicode/eg-openapi-request-validator':
    package: '@marmicode/eg-openapi-request-validator'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
